### PR TITLE
[IMP] meyko: Add customized landed cost by included products T#54261

### PR DESCRIPTION
**Pull request by rolandojduartem**
It was added stock_landed_cost module.
stock_landed_cost_lines was added two new fields to get products from
pickings and save included products to apply the landed costs.
stock_landed_cost was developed compute_landed_cost inheritance to apply
the
customized landed cost by included products from pickings
I added a view from for cost lines to show the included products in the
respective landed cost. Also, I added three demo products with fifo for
test purposes.
Reference:
https://github.com/odoo/odoo/blob/83b5eb13a4b2404a14fa7df74d87536253ee6dd6/addons/stock_landed_costs/models/stock_landed_cost.py#L212

### CODE REVIEW

**Comment by hugho-ad** [comment]
@rizzopablovauxoo 

could you move this to staging pls, 
15.0-landed_costs_products-t54261-dev-rolando

in order to test the latest developed by @rolandojduartem 


@luistorresm 
you should not use any more this branch
150-mix_changes-goliveirab

was already merged 
https://github.com/Vauxoo/meyko/pull/19

**Comment by luistorresm** [comment]
> @rizzopablovauxoo
> 
> could you move this to staging pls, 15.0-landed_costs_products-t54261-dev-rolando
> 
> in order to test the latest developed by @rolandojduartem
> 
> @luistorresm you should not use any more this branch 150-mix_changes-goliveirab
> 
> was already merged #19

👍 

@rolandojduartem 

Could you update the Honduras repo on this PR?  

Regards

**Comment by hugho-ad** [comment]
@luistorresm 

done!

cc  @rizzopablovauxoo

**Comment by hugho-ad** [comment]
@rizzopablovauxoo 


this won't be merged?

**Comment by rizzopablovauxoo** [comment]
> @rizzopablovauxoo
> 
> this won't be merged?

Yes, it should be! 

(last time I merged something you told me not to, this time I should do it? :-) sry!)

**Comment by hugho-ad** [comment]
I told you don't merge PR without explicit technicall approvals
You can merge this, just make sure mr's realted with this are already merged

For example, for vauxoo/meyko submodule, it said commit 1b5ecf
https://git.vauxoo.com/vauxoo/meyko/-/merge_requests/11
and it's already on stable 
image


review the one on Honduras repos or ask someone technically if it's ready

image


regards!

cc @cmedrano55

**Pull request merged**
